In [25]:
import copy

sol=[]

def make_path(m, n, y, x, path):
    global sol
    if m-1==y and n-1==x :
#         path.append([y,x])
        path.add(y*m+x)
#         print(path)
        sol.append(path)
        return
    if m-1>y:
#         path2 = path[:]
#         path2.append([y,x])
        path2 = copy.copy(path)
        path2.add(y*m+x)
        make_path(m, n, y+1, x, path2)
    if n-1>x:
#         path3 = path[:]
#         path3.append([y,x])
        path3 = copy.copy(path)
        path3.add(y*m+x)
        make_path(m, n, y, x+1, path3)

def solution(m, n, puddles):
    global sol
    sol=[]
    answer = 0
    m,n = n,m
    newpud = set()
    for p in puddles:
        newpud.add( (p[1]-1)*m+(p[0]-1) )
    path=set()
    make_path(m, n, 0, 0, path)
#     print(sol)
    cnt=0
    for s in sol:
        if len(s & newpud)==0:
            cnt+=1
            
    answer = cnt
    print(answer)
    
    return answer



In [26]:
solution(4,3,[[2,2]])

4


4

In [29]:
import copy

sol=[]

def make_path(m, n, y, x, path):
    global sol
    if m-1==y and n-1==x :
        path.add(y*m+x)
        sol.append(path)
        return
    if m-1>y:
        path2 = copy.copy(path)
        path2.add(y*m+x)
        make_path(m, n, y+1, x, path2)
    if n-1>x:
        path3 = copy.copy(path)
        path3.add(y*m+x)
        make_path(m, n, y, x+1, path3)

def solution(m, n, puddles):
    global sol
    sol=[]
    answer = 0
    m,n = n,m
    newpud = set()
    for p in puddles:
        newpud.add( (p[1]-1)*m+(p[0]-1) )
    path=set()
    make_path(m, n, 0, 0, path)
    cnt=0
    for s in sol:
        if len(s & newpud)==0:
            cnt+=1
    
    answer = cnt
    print(answer)
    
    return answer



In [30]:
solution(4,3,[[2,2]])

4


4

In [31]:
## Grid

In [48]:
import numpy as np


def solution(m, n, puddles):
    answer = 0
    m,n = n,m
    newpud = set()
    for p in puddles:
        newpud.add( (p[1]-1)*m+(p[0]-1) )
        
    grid = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            v=i*m+j
            if i==0 and j==0:
                grid[i,j] =1
            if v in newpud:
                grid[i,j] = 0
            else:
                if i-1>=0:
                    cnt = grid[i-1, j]
                    if cnt>0:
                        grid[i,j] += cnt
                        grid[i,j] %= 1000000007
                if j-1>=0:
                    cnt = grid[i, j-1]
                    if cnt>0:
                        grid[i,j] += cnt
                        grid[i,j] %= 1000000007
                    
    print(grid)
    answer = grid[m-1, n-1]
    print(answer)
    
    return answer


In [49]:
solution(4,3, [[2,2]])

[[1. 1. 1. 1.]
 [1. 0. 1. 2.]
 [1. 1. 2. 4.]]
4.0


4.0

In [50]:
import numpy as np


def solution(m, n, puddles):
    answer = 0
    m,n = n,m
    newpud = set()
    for p in puddles:
        newpud.add( (p[1]-1)*n+(p[0]-1) )
        
    grid = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            v=i*n+j
            if i==0 and j==0:
                grid[i,j] =1
            if v in newpud:
                grid[i,j] = 0
            else:
                if i-1>=0:
                    cnt = grid[i-1, j]
                    if cnt>0:
                        grid[i,j] += cnt
                        grid[i,j] %= 1000000007
                if j-1>=0:
                    cnt = grid[i, j-1]
                    if cnt>0:
                        grid[i,j] += cnt
                        grid[i,j] %= 1000000007
    # print(grid)
    answer = grid[m-1, n-1] % 1000000007
    print(answer)
    return answer