In [1]:

import numpy as np



In [27]:
board = np.asarray([[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,4,0,0,0],[0,0,0,0,0,4,4,0,0,0],[0,0,0,0,3,0,4,0,0,0],[0,0,0,2,3,0,0,0,5,5],[1,2,2,2,3,3,0,0,0,5],[1,1,1,0,0,0,0,0,0,5]])


In [28]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 4, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 4, 0, 0, 0],
       [0, 0, 0, 2, 3, 0, 0, 0, 5, 5],
       [1, 2, 2, 2, 3, 3, 0, 0, 0, 5],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 5]])

In [150]:
import numpy as np

canb = [ np.asarray([
[1, 0, 0],
[1, 1, 1]
]) ,
        np.asarray([
[0, 0, 1],
[1, 1, 1]
]) ,
        np.asarray([
[0, 1, 0],
[1, 1, 1]
]) ,
        np.asarray([
[1, 0],
[1, 0],
[1, 1]
]) ,
        np.asarray([
[0, 1],
[0, 1],
[1, 1]
]) ,
]

# mode=0이면 원본일부. 사각형 블록 board 원본. (다른 블록표시 유지) 
# mode=1이면 copy본. 사각형 블록 추출(1,0로 표시)
def get_block(board, num, mode):
    r = np.where(board==num)
    ry, rx = r[0], r[1]
#     print(ry,rx)
    if len(ry)==0:
        return -1,-1,-1,-1,[]
    y1=np.min(ry)
    y2=np.max(ry)
    x1=np.min(rx)
    x2=np.max(rx)
#     print(y1,y2,x1,x2)
    if mode==1:
        found = board[y1:y2+1,x1:x2+1].copy()
        found[found!=num]=0
        found[found==num]=1
    elif mode==0:
        found = board[y1:y2+1,x1:x2+1]
#     print(found.shape)
#     print(found)
    return y1,y2,x1,x2, found


def check_breakshape(board):
    num = np.max(board)
    breakable_list = []
    for i in range(1,num+1):
        y1,y2,x1,x2, found = get_block(board, i, 1)
        if y1==-1:
            continue

        for idx,p in enumerate(canb):
            if p.shape==found.shape:
                if np.all(p==found):
#                     print('match!')
#                     print(p)
                    breakable_list.append([i, y1, idx]) # 가장 높은 위치 기록.
    
    # 정렬시 주의사항!. 동일 높이인 경우!, 2차로 우선순위가 필요하다.
    # 동일 높이지만, 높이2, 높이3인 것이 있으면 높이2의 바닥이 높기 때문에
    # 먼저 깨야 한다.  
    breakable_list = sorted(breakable_list, key=lambda x: x[2])
    breakable_list=sorted(breakable_list, key=lambda x: x[1] )
#     print(breakable_list)
    return breakable_list    


def break_block(board, num, idx):
    y1,y2,x1,x2,found = get_block(board, num, 0)
    print('org', y1,y2, x1,x2)
    print(found)
    print('pattern')
    print(canb[idx])
    zeroindex = np.where(canb[idx][0]==0) 
    print('zero index=', zeroindex )
    # zero index위쪽이 다 열려있어야 깰 수 있다.
    ylimit = y1+1
    if canb[idx].shape[0]==3:
        ylimit +=1 # 깊이를 하나 더 확인해봐야 한다.
    block=0
    for x in zeroindex:
#         print('free check: num=', num)
#         print(board[:ylimit,x1+x])     
        block += np.sum(board[:ylimit,x1+x])
    if block==0:
        # break!
        print('break!', num)
        board[board==num]=0
        return 1
    return 0
    
    
def solution(board):
    answer = 0
    board = np.asarray(board)
    breakable_list = check_breakshape(board)
    for b in breakable_list:
        print(board)
        print('')
        num = b[0]
        idx = b[2]
        answer += break_block(board, num, idx)
    print(board)
    print('')
    return answer



In [151]:
# board = np.asarray([[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,4,0,0,0],[0,0,0,0,0,4,4,0,0,0],[0,0,0,0,3,0,4,0,0,0],[0,0,0,2,3,0,0,0,5,5],[1,2,2,2,3,3,0,0,0,5],[1,1,1,0,0,0,0,0,0,5]])

# board = np.asarray(
#       [[0, 0, 0,14,14, 0,11, 0,12, 0],
#        [0, 0, 0,14, 0, 0,11,12,12, 0],
#        [0, 0,15,14, 9, 0,11,11,12, 0],
#        [0,15,15, 9, 9, 9, 0, 0, 0, 0],
#        [13,13,15, 7, 0, 0, 4, 0, 0, 0],
#        [13, 0, 0, 7, 0, 4, 4, 0, 0, 0],
#        [13, 6, 7, 7, 3, 0, 4,12,12, 0],
#        [6, 6, 6, 2, 3, 0, 8, 8,12, 5],
#        [1, 2, 2, 2, 3, 3, 0, 8,12, 5],
#        [1, 1, 1, 0, 0, 0, 0, 8, 5, 5]]
# )

board = np.asarray(
[[0,0,0,0,0,0,0,6,0,0]
,[0,0,0,0,5,0,6,6,6,0]
,[0,0,0,4,5,5,5,0,0,0]
,[0,0,3,4,4,4,8,0,0,0]
,[1,2,3,3,3,8,8,0,0,0]
,[1,2,2,2,0,7,8,0,0,0]
,[1,1,0,0,7,7,7,0,0,0]]

)

solution(board)
    

[[0 0 0 0 0 0 0 6 0 0]
 [0 0 0 0 5 0 6 6 6 0]
 [0 0 0 4 5 5 5 0 0 0]
 [0 0 3 4 4 4 8 0 0 0]
 [1 2 3 3 3 8 8 0 0 0]
 [1 2 2 2 0 7 8 0 0 0]
 [1 1 0 0 7 7 7 0 0 0]]

org 0 1 6 8
[[0 6 0]
 [6 6 6]]
pattern
[[0 1 0]
 [1 1 1]]
zero index= (array([0, 2], dtype=int64),)
break! 6
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 4 5 5 5 0 0 0]
 [0 0 3 4 4 4 8 0 0 0]
 [1 2 3 3 3 8 8 0 0 0]
 [1 2 2 2 0 7 8 0 0 0]
 [1 1 0 0 7 7 7 0 0 0]]

org 1 2 4 6
[[5 0 0]
 [5 5 5]]
pattern
[[1 0 0]
 [1 1 1]]
zero index= (array([1, 2], dtype=int64),)
break! 5
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 3 4 4 4 8 0 0 0]
 [1 2 3 3 3 8 8 0 0 0]
 [1 2 2 2 0 7 8 0 0 0]
 [1 1 0 0 7 7 7 0 0 0]]

org 2 3 3 5
[[4 0 0]
 [4 4 4]]
pattern
[[1 0 0]
 [1 1 1]]
zero index= (array([1, 2], dtype=int64),)
break! 4
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 8 0 0 0]
 [1 2 3 3 3 8 8 0 0 0]
 [1 2 2 2 0 7 8 0 0 0]
 [1 1 0 0 7 7 7 0 0 0]]

org 3 4 2 4
[[3 0 0]


6