In [71]:
import numpy as np

def solution(food_times, k):
    n = len(food_times)
    i=0 # 인덱스용
    j=0 # 시간
    
    food_times = np.asarray(food_times)
    food_index = list(range(1, n+1))
    
    # 아래 조건을 빠뜨려서 런타임 에러가 났음.
    if np.sum(food_times)<=k:
        return -1
    
    while k>0:
        n = len(food_times)
        if n==0:
            break
        min_idx = np.argmin(food_times)
        min_food = food_times[min_idx]
        
        v = k//n  # 5초//3개 = 1
        if v==0:
            break
        
        if v>min_food:
            v=min_food
        
        elap=v*n
        k-=elap
        food_times = food_times - v
        
        zerocolumns=[]
        for z in range(n):
            if food_times[z]==0:
                zerocolumns.append(z)
        if len(zerocolumns)>0:
            zerocolumns.reverse()
            for z in zerocolumns:
                food_times = np.delete(food_times, z)
                del food_index[z]
        else:
            print('no zero?? ')
#         print(food_times)
#         print(food_index)
    print('remain k=', k)
    print(food_times)
    print(food_index)
    if n==0:
        return -1
    
    answer = food_index[k]
    print(answer)
    return answer

In [73]:
k=155
food_times=[13,10,8,21,15,44,10,87,25]
solution(food_times,k)

no zero?? 
remain k= 1
[18 61]
[6, 8]
8


8

In [152]:
import numpy as np

def solution(food_times, k):
    n = len(food_times)
    food_times = np.asarray(food_times)
#     if np.sum(food_times)<=k:
#         return -1
    
    # 정렬을 해서 앞에서 부터 떨어지게 만든다.
    print(food_times)
    food_index = np.argsort(food_times)
    food_index += 1
    food_times=np.sort(food_times)
    print('indxe=', food_index)
    print(food_times)
    
    startidx=0 # 스캔시작 위치
    remaincnt=n  # 남은 음식종류 수
    
    # 미리 최대한 계산하여 한 번에 뺀다.
    elap=0
    v=0
    for i in range(n):
        if food_times[i]==0:
            continue
        startidx=i
        tmp = food_times[i]*(n-i)
        # chck avail?
        if tmp>=k:
            break
        k-=tmp
        food_times[i:] = food_times[i:] - food_times[i]
    print('# preprocess')
    print('k=', k, 'startidx=', startidx)
    print('food_times=', food_times)
    
    
    # 남은 것은 순차적으로 처리
    print('# process')
    loopcnt=0
    while k>0:
        loopcnt+=1
        print('debug: loop=', loopcnt)
        remaincnt = n-startidx
        if remaincnt==0:
            break
#         min_idx = np.argmin(food_times)
#         min_food = food_times[min_idx]
        min_food = food_times[startidx]
        v = k//remaincnt  # 5초//3개 = 1
        if v==0:
            break
        if v>min_food:
            v=min_food
        elap=v*remaincnt
        k-=elap
        food_times[startidx:] = food_times[startidx:] - v
        zerocnt=0
        for i in range(startidx,n):
            if food_times[i]==0:
                zerocnt+=1
            else:
                break
        startidx+=zerocnt  
            
#         print(food_times, 'startidx=', startidx, 'k=',k, 'elap=', elap, 'v=', v, 'rn=', remaincnt)
#     print('remain k=', k)
#     print(food_times)
#     print(food_index)
    if remaincnt==0:
        return -1
    oo = np.sort(food_index[startidx:])
    answer = oo[k]
    return answer

In [153]:
k=5
food_times=[3,1,2]
solution(food_times,k)

[3 1 2]
indxe= [2 3 1]
[1 2 3]
# preprocess
k= 2 startidx= 1
food_times= [0 1 2]
# process
debug: loop= 1


1

In [154]:
k=55
food_times=[13,10,8,21,15,44,10,87,25]
solution(food_times,k)

[13 10  8 21 15 44 10 87 25]
indxe= [3 2 7 1 5 4 9 6 8]
[ 8 10 10 13 15 21 25 44 87]
# preprocess
k= 55 startidx= 0
food_times= [ 8 10 10 13 15 21 25 44 87]
# process
debug: loop= 1
debug: loop= 2


2

In [155]:
k=5000
food_times=[113,110,108,121,5115,108,110,187,25, 3]
solution(food_times,k)

[ 113  110  108  121 5115  108  110  187   25    3]
indxe= [10  9  3  6  2  7  1  4  8  5]
[   3   25  108  108  110  110  113  121  187 5115]
# preprocess
k= 3928 startidx= 9
food_times= [   0    0    0    0    0    0    0    0    0 4928]
# process
debug: loop= 1


5

In [156]:
# 마지막에 인덱스값을 확인하는 과정에서 정렬이 되었다는 것을 고려하여
# 순서를 복원해야 함.
# 마지막의 order는 [1, 5, 4, 9, 8] 번호로 나와있는데. 이것은 크기로 정렬된 순서.
# 원래의 순서로 변경해야... 1, 4, 5, 8, 9 순번이 맞는것이다. 이것을 순서대로 k indexing.

In [157]:
np.sum(food_times)

6000

In [172]:
import numpy as np

def solution(food_times, k):
    n = len(food_times)
    food_times = np.asarray(food_times)
    if np.sum(food_times)<=k:
        return -1
    
    # 정렬을 해서 앞에서 부터 떨어지게 만든다.
    print(food_times)
    food_index = np.argsort(food_times)
    food_index += 1
    food_times=np.sort(food_times)
    print('indxe=', food_index)
    print(food_times)
    
    startidx=0 # 스캔시작 위치
    remaincnt=n  # 남은 음식종류 수
    
    # 미리 최대한 계산하여 한 번에 뺀다.
    elap=0
    v=0
    removeidx = -1
    for i in range(n):
        tmp = (food_times[i]-v)*(n-i)
        # chck avail?
        if elap+tmp>=k:
            break
        elap+=tmp
        v = food_times[i]
        removeidx = i
    
    food_times = food_times - v
    k -= elap
    print('# preprocess')
    print('k=', k, 'startidx=', startidx)
    print('food_times=', food_times)
    
    # 크기를 줄인다.
    startidx = removeidx+1
    food_times = food_times[startidx:]
    food_index = food_index[startidx:]
    startidx=0
    n = len(food_times)
    remaincnt=n
    print('food_times=', food_times)
    
    # 남은 것은 순차적으로 처리
    print('# process')
    loopcnt=0
    while k>0:
        loopcnt+=1
        print('debug: loop=', loopcnt)
        remaincnt = n-startidx
        if remaincnt==0:
            break
        min_food = food_times[startidx]
        v = k//remaincnt  # 5초//3개 = 1
        if v==0:
            break
        if v>min_food:
            v=min_food
        elap=v*remaincnt
        k-=elap
        food_times = food_times - v
        zerocnt=0
        for i in range(startidx,n):
            if food_times[i]==0:
                zerocnt+=1
            else:
                break
        startidx+=zerocnt  
            
#         print(food_times, 'startidx=', startidx, 'k=',k, 'elap=', elap, 'v=', v, 'rn=', remaincnt)
#     print('remain k=', k)
#     print(food_times)
#     print(food_index)
    if remaincnt==0:
        return -1
    oo = np.sort(food_index[startidx:])
    answer = oo[k]
    return answer

In [173]:
k=5000
food_times=[113,110,108,121,5115,108,110,187,25, 3]
solution(food_times,k)

[ 113  110  108  121 5115  108  110  187   25    3]
indxe= [10  9  3  6  2  7  1  4  8  5]
[   3   25  108  108  110  110  113  121  187 5115]
# preprocess
k= 3928 startidx= 0
food_times= [-184 -162  -79  -79  -77  -77  -74  -66    0 4928]
food_times= [4928]
# process
debug: loop= 1


5